//! Save lifecycle scenarios.

use super::*;

/// The 20-second autosave used to rewrite every chunk the player had
/// ever loaded, forever — the `modified` flag was set on load and never
/// cleared, so an hour of walking turned each autosave into a few
/// hundred synchronous file writes on the main thread. That is the
/// periodic hitch, and this is the shape of the fix: a write clears the
/// flag, and only a real edit sets it again.
#[test]
fn the_autosave_writes_only_what_changed_since_the_last_one() {
    let reg = base_reg();
    let dir = tmp_dir("autosave-churn");
    let mut w = World::new(9, dir.clone(), reg.clone());
    w.ensure_chunk(tchunk(0, 0));
    let stone = b(&reg, "base:stone");
    let top = w.surface_height(3, 3);
    w.set_block(3, top + 1, 3, stone);
    save_world(&mut w);
    let file = crate::world::region::region_path(&dir, tchunk(0, 0));
    assert!(file.exists(), "the edited chunk is written");

    // Deleting the file is the probe: if the next autosave puts it
    // back, the chunk was queued for writing with nothing to write.
    std::fs::remove_file(&file).unwrap();
    save_world(&mut w);
    assert!(!file.exists(), "an unchanged chunk is not rewritten");

    // ...and one more edit puts it straight back in the queue.
    w.set_block(4, top + 1, 4, stone);
    save_world(&mut w);
    assert!(file.exists(), "an edited chunk saves again");
}

#[test]
fn save_reports_every_failed_component_and_retries_dirty_chunks() {
    let reg = base_reg();
    let root = tmp_dir("save-report");
    let blocked = root.join("not-a-directory");
    std::fs::create_dir_all(&blocked).unwrap();
    let mut w = World::new(9, blocked.clone(), reg.clone());
    let pos = tchunk(0, 0);
    assert!(w.ensure_chunk(pos));
    let stone = b(&reg, "base:stone");
    let top = w.surface_height(3, 3);
    w.set_block(3, top + 1, 3, stone);

    // Inject a write failure after a real dirty chunk exists. Unreadable
    // terrain is no longer regenerated by ensure_chunk during a read failure.
    let preserved = root.join("preserved-save");
    std::fs::rename(&blocked, &preserved).unwrap();
    std::fs::write(&blocked, b"occupied").unwrap();

    let failed = w.save_modified();
    let components: std::collections::HashSet<&str> = failed
        .failures
        .iter()
        .map(|failure| failure.component.as_str())
        .collect();
    for component in [
        "save directory",
        "world metadata",
        "block palette",
        "block entities",
        "animals",
        "regional ire",
        "bloom ledger",
        "long winter",
        "bloom exhaustion",
        "hearts",
        "animal seed marks",
        "player-touched marks",
        "random-tick stamps",
    ] {
        assert!(
            components.contains(component),
            "{component} failure is visible: {}",
            failed.summary()
        );
    }
    assert_eq!(
        failed.chunks_saved, 0,
        "a chunk cannot precede its failed palette"
    );

    std::fs::remove_file(&blocked).unwrap();
    std::fs::rename(&preserved, &blocked).unwrap();
    let retry = w.save_modified();
    assert!(retry.is_ok(), "retry succeeds: {}", retry.summary());
    assert_eq!(retry.chunks_saved, 1, "the dirty chunk was retained");

    w.set_block(4, top + 1, 4, stone);
    w.fail_chunk_save_for_test(pos, true);
    let chunk_failure = w.save_modified();
    assert_eq!(chunk_failure.chunks_saved, 0);
    assert!(
        chunk_failure
            .failures
            .iter()
            .any(|failure| failure.component == format!("chunk {pos:?}")),
        "chunk failure has coordinates: {}",
        chunk_failure.summary()
    );
    w.fail_chunk_save_for_test(pos, false);
    let chunk_retry = w.save_modified();
    assert!(chunk_retry.is_ok(), "chunk retry succeeds");
    assert_eq!(chunk_retry.chunks_saved, 1, "failed chunk stayed dirty");
}

/// A chunk that came off disk already matches its file. Reloading a
/// world and walking around must not re-dirty everything it touches.
#[test]
fn a_chunk_read_from_disk_is_clean_until_something_edits_it() {
    let reg = base_reg();
    let dir = tmp_dir("autosave-reload");
    let stone = b(&reg, "base:stone");
    let top = {
        let mut w = World::new(9, dir.clone(), reg.clone());
        w.ensure_chunk(tchunk(0, 0));
        let top = w.surface_height(3, 3);
        w.set_block(3, top + 1, 3, stone);
        save_world(&mut w);
        top
    };
    let file = crate::world::region::region_path(&dir, tchunk(0, 0));
    assert!(file.exists());

    let mut w = World::load_or_create(dir.clone(), reg.clone()).unwrap();
    w.ensure_chunk(tchunk(0, 0));
    assert_eq!(w.get_block(3, top + 1, 3), stone, "the edit came back");
    std::fs::remove_file(&file).unwrap();
    save_world(&mut w);
    assert!(
        !file.exists(),
        "a freshly loaded, untouched chunk is not rewritten"
    );
}

/// Stamps mean nothing without the clock they were written against.
#[test]
fn stamps_from_a_different_day_length_are_dropped_not_misread() {
    let reg = base_reg();
    let dir = tmp_dir("stamps-version");
    {
        let mut w = World::new(9, dir.clone(), reg.clone());
        w.ensure_chunk(tchunk(0, 0));
        let mut rng = 1u32;
        w.random_tick(&mut rng);
        save_world(&mut w);
    }
    let w = World::load_or_create(dir.clone(), reg.clone()).unwrap();
    assert!(w.stamp_count() > 0, "same clock, stamps come back");

    // A pre-retune file: the old headerless (x, z, time) triples.
    let mut old = Vec::new();
    old.extend_from_slice(&0i32.to_le_bytes());
    old.extend_from_slice(&0i32.to_le_bytes());
    old.extend_from_slice(&123.0f64.to_le_bytes());
    std::fs::write(dir.join("stamps"), &old).unwrap();
    let w = World::load_or_create(dir.clone(), reg.clone()).unwrap();
    assert_eq!(
        w.stamp_count(),
        0,
        "a stamp on another clock is discarded, not read as days of absence"
    );
}

#[test]
fn a_world_survives_a_save_and_reload_across_several_regions() {
    // Chunks live 32x32 to a face-local region file. Sample explicit chunks
    // on both sides of several region boundaries and on all six faces, edit
    // each, save, drop the world, and read it all back.
    let reg = base_reg();
    let dir = tmp_dir("region-round-trip");
    let stone = b(&reg, "base:stone");
    let planks = b(&reg, "base:planks");

    let mut edits = Vec::new();
    {
        let mut w = World::new(4242, dir.clone(), reg.clone());
        for face in crate::planet::Face::ALL {
            for cu in [0u16, 31, 32, 255, 256, 480, 511] {
                for cv in [0u16, 31, 32, 255, 256] {
                    let chunk = crate::planet::ChunkPos::new(face, cu, cv).unwrap();
                    w.ensure_chunk(chunk);
                    let surface = crate::planet::SurfacePos::new(
                        face,
                        cu * crate::chunk::CHUNK_X as u16 + 3,
                        cv * crate::chunk::CHUNK_Z as u16 + 5,
                    )
                    .unwrap();
                    let y = w.surface_height_at(surface) + 1;
                    let block = if cu.is_multiple_of(2) { stone } else { planks };
                    let at = block_pos(surface, y);
                    w.set_block_at(at, block);
                    edits.push((at, block));
                }
            }
        }
        save_world(&mut w);
    }
    assert!(edits.len() > 200, "enough chunks to span many regions");

    // Several region files, not hundreds of chunk files.
    let files: Vec<String> = crate::planet::Face::ALL
        .into_iter()
        .flat_map(|face| {
            std::fs::read_dir(dir.join(face.name()))
                .into_iter()
                .flatten()
                .filter_map(Result::ok)
                .map(|entry| entry.file_name().to_string_lossy().into_owned())
        })
        .collect();
    let regions = files.iter().filter(|f| f.ends_with(".wfr")).count();
    let loose = files.iter().filter(|f| f.ends_with(".wfc")).count();
    assert!(regions > 1, "the span crosses region boundaries");
    assert_eq!(loose, 0, "no per-chunk files are written any more");
    assert!(
        regions < edits.len(),
        "{regions} region files for {} chunks — the whole point is fewer",
        edits.len()
    );

    let mut w = World::load_or_create(dir, reg.clone()).unwrap();
    for (at, want) in edits {
        w.ensure_chunk(crate::planet::ChunkPos::from_surface(at.surface()));
        assert_eq!(
            w.get_block_at(at),
            want,
            "block at {at:?} did not survive the round trip"
        );
    }
}
