//! Empty content graph and engine-owned sentinel definitions.

use crate::registry::{Registry, BlockDef, BlockId, AIR, MaterialClass, MaterialVector};
use std::collections::{BTreeMap, HashMap};

pub(super) fn empty() -> Registry {
    Registry {
        content_hash: 0,
        asset_snapshot: None,
        blocks: Vec::new(),
        items: Vec::new(),
        recipes: Vec::new(),
        ores: Vec::new(),
        block_by_name: HashMap::new(),
        item_by_name: HashMap::new(),
        water_ids: [AIR; 8],
        lava_ids: [AIR; 8],
        unknown_block: AIR,
        mods: Vec::new(),
        smelts: Vec::new(),
        forge_salvage: Vec::new(),
        fuels: Vec::new(),
        bloomery: Vec::new(),
        worked: Vec::new(),
        kiln: Vec::new(),
        kiln_base: None,
        tags: HashMap::new(),
        tex_files: Vec::new(),
        tex_names: Vec::new(),
        animals: Vec::new(),
        npcs: Vec::new(),
        dialogues: Vec::new(),
        quests: Vec::new(),
        structures: Vec::new(),
        pieces: Vec::new(),
        pools: Vec::new(),
        assemblies: Vec::new(),
        settlements: Vec::new(),
        gates: Vec::new(),
        gate_for_block: HashMap::new(),
        loots: HashMap::new(),
        modes: Vec::new(),
        skills: crate::skills::SkillTree::default(),
        machines: Vec::new(),
        nests: Vec::new(),
        screens: Vec::new(),
        material_errors: Vec::new(),
        arcane_registry: crate::arcane::ResonanceRegistry::base(),
        arcane_sites: Vec::new(),
        arcane_ecology: BTreeMap::new(),
        workings: BTreeMap::new(),
        preparations: BTreeMap::new(),
        dross_scars: BTreeMap::new(),
        arcane_errors: Vec::new(),
    }
}

pub(super) fn air(reg: &mut Registry) {
    // Air (id 0) and the unknown-block placeholder are engine-registered.
    let air = BlockDef {
        name: "base:air".into(),
        label: "Air".into(),
        tiles: [0; 6],
        hardness: None,
        tool: None,
        requires_tool: false,
        drops: None,
        solid: false,
        opaque: false,
        interaction: None,
        min_tier: 0,
        water_level: None,
        lava: false,
        cross: false,
        burns: 0,
        floats: false,
        shape: None,
        crop_next: None,
        crop_chance: 0.0,
        crop_any_soil: false,
        harvest: None,
        light_emit: 0,
        sapling: None,
        bonus_drop: None,
        brush: None,
        height: None,
        falls: false,
        glass: false,
        light_filter: [true; 3],
        light_rgb: [0, 0, 0],
        fert_tiles: None,
        crop_family: 0,
        material_class: MaterialClass::Renewable,
        materials: MaterialVector::new(),
        dismantles_to: None,
        heat_retention: 0,
        arcane: None,
        arcane_ecology: None,
        observation: None,
        discovery_fixture: None,
    };
    reg.block_by_name.insert(air.name.clone(), BlockId(0));
    reg.blocks.push(air);
}

pub(super) fn unknown(reg: &mut Registry) {
    // The unknown-block placeholder.
    let unk = BlockId(reg.blocks.len() as u16);
    reg.blocks.push(BlockDef {
        name: "base:unknown".into(),
        label: "Unknown".into(),
        tiles: [crate::atlas::UNKNOWN_SLOT; 6],
        hardness: Some(0.5),
        tool: None,
        requires_tool: false,
        drops: None,
        solid: true,
        opaque: true,
        interaction: None,
        min_tier: 0,
        water_level: None,
        lava: false,
        cross: false,
        burns: 0,
        floats: false,
        shape: None,
        crop_next: None,
        crop_chance: 0.0,
        crop_any_soil: false,
        harvest: None,
        light_emit: 0,
        sapling: None,
        bonus_drop: None,
        brush: None,
        height: None,
        falls: false,
        glass: false,
        light_filter: [true; 3],
        light_rgb: [0, 0, 0],
        fert_tiles: None,
        crop_family: 0,
        material_class: MaterialClass::TransformativeFinite,
        materials: MaterialVector::new(),
        dismantles_to: None,
        heat_retention: 0,
        arcane: None,
        arcane_ecology: None,
        observation: None,
        discovery_fixture: None,
    });
    reg.block_by_name.insert("base:unknown".into(), unk);
    reg.unknown_block = unk;
}
