//! Texture atlas assembly, stable slot mapping, and public API.
//!
//! By default the atlas is generated procedurally (resolution set by
//! `WILDFORGE_TILE_PX`, default 32). If `assets/atlas.png` exists it is
//! loaded instead, so hand-drawn or AI-generated packs drop in without a
//! recompile. `WILDFORGE_EXPORT_ATLAS=path.png` dumps the procedural atlas
//! as a template.
//!
//! All UV math in the game uses tile fractions (1/16 of the atlas), so any
//! square atlas whose side is a multiple of 16 works.

pub const ATLAS_TILES: u32 = 32;
/// Atlas slot = row * 16 + col. Rows 0-2 are built-in procedural tiles.
pub const UNKNOWN_SLOT: u16 = 15;
pub const CRACK_SLOT: u16 = 16; // stages 16..=19
pub const FIRST_FREE_SLOT: u16 = 240; // built-ins own slots 0-239 (32-wide grid)

/// Built-in procedural tile names usable as `@name` in mod TOML.
pub fn builtin_slots() -> std::collections::HashMap<String, u16> {
    [
        ("grass_top", 0u16),
        ("grass_side", 1),
        ("dirt", 2),
        ("stone", 3),
        ("cobblestone", 4),
        ("sand", 5),
        ("gravel", 6),
        ("log_side", 7),
        ("log_top", 8),
        ("leaves", 9),
        ("planks", 10),
        ("bedrock", 11),
        ("water", 12),
        ("table_top", 13),
        ("table_side", 14),
        ("stick", 32),
        ("wood_pickaxe", 33),
        ("stone_pickaxe", 34),
        ("wood_axe", 35),
        ("stone_axe", 36),
        ("wood_shovel", 37),
        ("stone_shovel", 38),
        ("snow", 39),
        ("ice", 40),
        ("cactus_side", 41),
        ("cactus_top", 42),
        ("birch_log", 43),
        ("birch_log_top", 44),
        ("birch_leaves", 45),
        ("spruce_log", 46),
        ("spruce_log_top", 47),
        ("spruce_leaves", 48),
        ("jungle_log", 49),
        ("jungle_log_top", 50),
        ("jungle_leaves", 51),
        ("acacia_log", 52),
        ("acacia_log_top", 53),
        ("acacia_leaves", 54),
        ("birch_planks", 55),
        ("spruce_planks", 56),
        ("jungle_planks", 57),
        ("acacia_planks", 58),
        ("copper_ore", 59),
        ("tin_ore", 60),
        ("copper_block", 61),
        ("bronze_block", 62),
        ("furnace", 63),
        ("raw_copper", 64),
        ("raw_tin", 65),
        ("copper_ingot", 66),
        ("tin_ingot", 67),
        ("bronze_ingot", 68),
        ("bronze_blend", 69),
        ("charcoal", 70),
        ("copper_pickaxe", 71),
        ("copper_axe", 72),
        ("copper_shovel", 73),
        ("bronze_pickaxe", 74),
        ("bronze_axe", 75),
        ("bronze_shovel", 76),
        ("farmland", 77),
        ("wheat_young", 78),
        ("wheat_ripe", 79),
        ("carrot_plant", 80),
        ("potato_plant", 81),
        ("bush_fruited", 82),
        ("bush_bare", 83),
        ("mushroom", 84),
        ("bread", 85),
        ("berry", 86),
        ("carrot", 87),
        ("potato", 88),
        ("baked_potato", 89),
        ("roasted_mushroom", 90),
        ("cactus_fruit", 91),
        ("jungle_fruit", 92),
        ("stew", 93),
        ("seeds", 94),
        ("wood_hoe", 96),
        ("stone_hoe", 97),
        ("copper_hoe", 98),
        ("bronze_hoe", 99),
        ("deer", 100),
        ("deer_face", 101),
        ("boar", 102),
        ("boar_face", 103),
        ("goat", 104),
        ("goat_face", 105),
        ("grouse", 106),
        ("grouse_face", 107),
        ("rabbit", 108),
        ("rabbit_face", 109),
        ("desert_hare", 110),
        ("snow_hare", 111),
        ("raw_venison", 112),
        ("cooked_venison", 113),
        ("raw_boar", 114),
        ("cooked_boar", 115),
        ("raw_chevon", 116),
        ("cooked_chevon", 117),
        ("raw_fowl", 118),
        ("cooked_fowl", 119),
        ("raw_rabbit", 120),
        ("cooked_rabbit", 121),
        ("hide", 122),
        ("leather", 123),
        ("feather", 124),
        ("hearty_stew", 125),
        ("wood_sword", 126),
        ("stone_sword", 127),
        ("copper_sword", 128),
        ("bronze_sword", 129),
        ("antler", 130),
        ("torch", 131),
        ("chest_side", 132),
        ("chest_top", 133),
        ("thornling", 134),
        ("dryad", 135),
        ("dryad_face", 136),
        ("emberkin", 137),
        ("rimewisp", 138),
        ("gravelurk", 139),
        ("wrathwood", 140),
        ("wrathwood_face", 141),
        ("thorn_bolt", 142),
        ("ember_bolt", 143),
        ("frost_bolt", 144),
        ("plant_fiber", 145),
        ("living_wood", 146),
        ("ember", 147),
        ("frost_shard", 148),
        ("heartwood", 149),
        ("hunting_bow", 150),
        ("warbow", 151),
        ("arrow", 152),
        ("leather_helmet", 153),
        ("leather_chestplate", 154),
        ("leather_leggings", 155),
        ("leather_boots", 156),
        ("bronze_helmet", 157),
        ("bronze_chestplate", 158),
        ("bronze_leggings", 159),
        ("bronze_boots", 160),
        ("oak_sapling", 161),
        ("birch_sapling", 162),
        ("spruce_sapling", 163),
        ("jungle_sapling", 164),
        ("acacia_sapling", 165),
        ("offering_stone", 166),
        ("bedroll", 167),
        ("iron_ore", 168),
        ("iron_block", 169),
        ("steel_block", 170),
        ("raw_iron", 171),
        ("iron_ingot", 172),
        ("steel_blend", 173),
        ("steel_ingot", 174),
        ("iron_pickaxe", 175),
        ("iron_axe", 176),
        ("iron_shovel", 177),
        ("iron_hoe", 178),
        ("iron_sword", 179),
        ("steel_pickaxe", 180),
        ("steel_axe", 181),
        ("steel_shovel", 182),
        ("steel_hoe", 183),
        ("steel_sword", 184),
        ("iron_helmet", 185),
        ("iron_chestplate", 186),
        ("iron_leggings", 187),
        ("iron_boots", 188),
        ("steel_helmet", 189),
        ("steel_chestplate", 190),
        ("steel_leggings", 191),
        ("steel_boots", 192),
        ("shears", 193),
        ("excavation_brush", 194),
        ("mossy_cobblestone", 195),
        ("cracked_masonry", 196),
        ("packed_earth", 197),
        ("old_coin", 198),
        ("etched_tablet", 199),
        ("charm_quiet", 200),
        ("charm_bark", 201),
        ("charm_hunger", 202),
        ("player_shirt", 203),
        ("player_face", 204),
        ("snowball", 205),
        ("rain_streak", 206),
        ("snow_flake", 207),
        ("firebrick", 208),
        ("bloomery", 209),
        ("bloomery_lit", 210),
        ("charcoal_block", 211),
        ("stone_anvil", 212),
        ("steel_bloom", 213),
        ("smith_hammer", 214),
        ("glass", 216),
        ("cobalt_ore", 217),
        ("cinnabar_ore", 218),
        ("manganese_ore", 219),
        ("verdigris_powder", 220),
        ("ochre_powder", 221),
        ("cobalt_powder", 222),
        ("cinnabar_powder", 223),
        ("manganese_powder", 224),
        ("teal_glass", 225),
        ("amber_glass", 226),
        ("blue_glass", 227),
        ("red_glass", 228),
        ("violet_glass", 229),
        ("kiln", 230),
        ("kiln_lit", 231),
        ("quern", 232),
        ("snow_trod", 233),
        ("player_skin", 234),
        ("player_hair", 235),
        ("player_trousers", 236),
        ("player_boot", 237),
        ("player_hair_top", 238),
        ("bucket", 239),
        ("bucket_water", crate::style::EXTRA_BASE + 5),
        ("forge", crate::style::EXTRA_BASE + 6),
        ("forge_lit", crate::style::EXTRA_BASE + 7),
        // Extra player bases live in the reserved region (style.rs
        // EXTRA_BASE) — the low builtin rows are full.
        ("player_hair_cropped", crate::style::EXTRA_BASE),
        ("player_hair_long", crate::style::EXTRA_BASE + 1),
        ("player_moustache", crate::style::EXTRA_BASE + 2),
        ("player_beard_trim", crate::style::EXTRA_BASE + 3),
        ("player_beard_full", crate::style::EXTRA_BASE + 4),
        ("unknown", 15),
        ("crack1", 16),
        ("crack2", 17),
        ("crack3", 18),
        ("crack4", 19),
    ]
    .into_iter()
    .map(|(k, v)| (k.to_string(), v))
    .collect()
}

mod packs;
mod procedural;
mod season;

pub use packs::{
    PackInfo, PackSource, build_atlas, discover_packs, embedded_base_tile, embedded_pack,
};
#[cfg(test)]
pub(crate) use packs::{apply_player_variants, discover_packs_in, export_tiles};
pub(crate) use procedural::{build_material, build_normal, build_procedural};
pub use season::season_tint;
