//! Serializable atlas census and diagnostic export report schemas.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AtlasCensus {
    pub cells: usize,
    pub cells_by_face: BTreeMap<String, usize>,
    pub physical_area: f64,
    pub land_area: f64,
    pub ocean_area: f64,
    pub land_fraction: f64,
    pub ocean_fraction: f64,
    pub continent_and_island_count: u32,
    pub elevation_histogram: Vec<u64>,
    pub boundary_cells: BTreeMap<String, u64>,
    pub detailed_boundary_cells: BTreeMap<String, u64>,
    pub plate_count: usize,
    pub craton_count: usize,
    pub major_continent_count: usize,
    pub chosen_geology_attempt: u8,
    pub rejected_geology_attempts: usize,
    pub largest_ocean_share: f64,
    pub bedrock_areas: BTreeMap<String, f64>,
    pub oceanic_age_histogram: Vec<u64>,
    pub volcanoes_by_source: BTreeMap<String, usize>,
    pub intrusions_by_kind: BTreeMap<String, usize>,
    pub deposits_by_mineral: BTreeMap<String, usize>,
    pub deposit_tonnage_by_mineral: BTreeMap<String, u64>,
    pub progression_sites_by_continent: BTreeMap<String, usize>,
    pub climate_zone_areas: BTreeMap<String, f64>,
    pub area_mean_temperature_c: f64,
    pub minimum_temperature_c: f32,
    pub maximum_temperature_c: f32,
    pub area_mean_precipitation_mm: f64,
    pub maximum_precipitation_mm: f32,
    pub area_mean_aridity: f64,
    pub maximum_aridity: f32,
    pub biome_areas: BTreeMap<u16, f64>,
    pub biome_area_by_latitude_band: BTreeMap<String, f64>,
    pub biome_area_by_continent: BTreeMap<String, f64>,
    pub biome_area_by_elevation_band: BTreeMap<String, f64>,
    pub biome_area_by_water_availability: BTreeMap<String, f64>,
    pub habitat_areas: BTreeMap<String, f64>,
    pub drainage_edge_count: u64,
    pub river_length_blocks: f64,
    pub river_receiver_distance_histogram: Vec<u64>,
    pub named_river_count: usize,
    pub maximum_discharge: f32,
    pub maximum_channel_width_blocks: f32,
    pub maximum_stream_order: u8,
    pub ocean_basin_count: usize,
    pub lake_count: usize,
    pub lake_classes: BTreeMap<String, usize>,
    pub terminal_lake_count: usize,
    pub exorheic_lake_count: usize,
    pub watershed_count: usize,
    pub floodplain_cells: u64,
    pub wetland_cells: u64,
    pub delta_cells: u64,
    pub estuary_cells: u64,
    pub baseline_surface_water_units: u128,
    pub voxel_volume_residual: i128,
    pub freshwater_units: u128,
    pub total_water_units: u128,
    pub aquifer_storage_units: u128,
    pub resource_site_count: usize,
    pub nearest_resource_distance_bands: BTreeMap<String, u64>,
    pub max_nearest_deposit_distance_blocks: BTreeMap<String, f64>,
    pub province_count: usize,
    pub heart_count: usize,
    pub country_route_count: usize,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AtlasExportReport {
    pub validation: String,
    pub layout: String,
    pub registered_layers: Vec<String>,
    pub exported_maps: Vec<String>,
    pub cell_count: usize,
    pub stage_elapsed_micros: BTreeMap<String, u64>,
    pub immutable_bytes: u64,
    pub dynamic_bytes: u64,
    pub water_cycle_bytes: u64,
    pub geology_bytes: u64,
    pub hydrology_bytes: u64,
    pub biome_bytes: u64,
    pub estimated_loaded_bytes: u64,
    pub peak_resident_bytes: Option<u64>,
    pub export_elapsed_micros: u64,
}
