[[feature]]
type = "ore"
block = "base:copper_ore"
replaces = "base:stone"
vein_size = 7
per_chunk = 8
y_range = [8, 72]

[[feature]]
type = "ore"
block = "base:tin_ore"
replaces = "base:stone"
vein_size = 5
per_chunk = 5
y_range = [8, 56]

[[feature]]
type = "ore"
block = "base:iron_ore"
replaces = "base:stone"
vein_size = 6
per_chunk = 4
y_range = [4, 48]

[[feature]]
type = "ore"
block = "base:cobalt_ore"
replaces = "base:stone"
vein_size = 4
per_chunk = 2
y_range = [4, 24]

[[feature]]
type = "ore"
block = "base:cinnabar_ore"
replaces = "base:stone"
vein_size = 4
per_chunk = 2
y_range = [16, 40]

[[feature]]
type = "ore"
block = "base:manganese_ore"
replaces = "base:stone"
vein_size = 3
per_chunk = 2
y_range = [4, 16]
