//! Committed atlas directories and bounded storage entry points.

use crate::planet_atlas::{AtlasError, AtlasManifest, PlanetAtlas};
use crate::planet_atlas::manifest::{validate_manifest};
use std::{fs};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

mod bundle;
mod mutable;
mod load;
pub(super) mod arcane;

pub(in crate::planet_atlas) const MAX_GENESIS_BYTES: u64 = 128 * 1024 * 1024;
pub(in crate::planet_atlas) const MAX_DYNAMIC_BYTES: u64 = 64 * 1024 * 1024;
pub(in crate::planet_atlas) const MAX_WATER_CYCLE_BYTES: u64 = 128 * 1024 * 1024;
pub(in crate::planet_atlas) const MAX_MANIFEST_BYTES: u64 = 1024 * 1024;
pub(in crate::planet_atlas) const MAX_HISTORY_BYTES: u64 = 16 * 1024 * 1024;
pub(in crate::planet_atlas) const MAX_GEOLOGY_BYTES: u64 = 16 * 1024 * 1024;
pub(in crate::planet_atlas) const MAX_HYDROLOGY_BYTES: u64 = 32 * 1024 * 1024;
pub(in crate::planet_atlas) const MAX_BIOMES_BYTES: u64 = 16 * 1024 * 1024;

pub(in crate::planet_atlas) const GENESIS_FILE: &str = "genesis.wfa";
pub(in crate::planet_atlas) const DYNAMIC_FILE: &str = "dynamic.wfd";
pub(in crate::planet_atlas) const DYNAMIC_BACKUP_FILE: &str = "dynamic.wfd.bak";
pub(in crate::planet_atlas) const WATER_CYCLE_FILE: &str = "water.wfw";
pub(in crate::planet_atlas) const WATER_CYCLE_BACKUP_FILE: &str = "water.wfw.bak";
pub(in crate::planet_atlas) const HISTORY_FILE: &str = "history.wfh";
pub(in crate::planet_atlas) const GEOLOGY_FILE: &str = "geology.wfg";
pub(in crate::planet_atlas) const HYDROLOGY_FILE: &str = "hydrology.wfy";
pub(in crate::planet_atlas) const BIOMES_FILE: &str = "biomes.wfb";
pub(in crate::planet_atlas) const MANIFEST_FILE: &str = "manifest.toml";

impl PlanetAtlas {
    /// Return the separately versioned atlas directory for a world root.
    pub fn planet_dir(world_dir: &Path) -> PathBuf {
        world_dir.join("planet")
    }

    /// Commit a brand-new atlas as one directory rename. Existing immutable
    /// genesis data is never overwritten or regenerated by this operation.
    pub fn write_new(&self, world_dir: &Path) -> Result<PathBuf, AtlasError> {
        self.validate()?;
        fs::create_dir_all(world_dir)?;
        let destination = Self::planet_dir(world_dir);
        if destination.exists() {
            return Err(AtlasError::AlreadyExists(destination));
        }
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let temporary = world_dir.join(format!(".planet.{}.{}.tmp", std::process::id(), stamp));
        fs::create_dir(&temporary)?;
        let result = (|| {
            self.write_bundle(&temporary)?;
            fs::rename(&temporary, &destination)?;
            sync_directory(world_dir)?;
            Ok(destination.clone())
        })();
        if result.is_err() {
            let _ = fs::remove_dir_all(&temporary);
        }
        result
    }

    /// Load a production atlas. Immutable data is always read from disk; it
    /// is never silently regenerated after an algorithm update.
    pub fn load(world_dir: &Path) -> Result<Self, AtlasError> {
        Self::load_planet_dir(&Self::planet_dir(world_dir), true)
    }

    /// Cheap world-browser predicate: only a validated, complete manifest is
    /// selectable. Payload checks happen when the world is actually opened.
    pub fn is_committed(world_dir: &Path) -> bool {
        let path = Self::planet_dir(world_dir).join(MANIFEST_FILE);
        let Ok(bytes) = read_bounded(&path, MAX_MANIFEST_BYTES) else {
            return false;
        };
        let Ok(text) = std::str::from_utf8(&bytes) else {
            return false;
        };
        let Ok(manifest) = toml::from_str::<AtlasManifest>(text) else {
            return false;
        };
        validate_manifest(&manifest, !cfg!(test)).is_ok()
    }

    #[cfg(test)]
    pub fn load_fixture(world_dir: &Path) -> Result<Self, AtlasError> {
        Self::load_planet_dir(&Self::planet_dir(world_dir), false)
    }
}

pub(in crate::planet_atlas) fn write_manifest(planet_dir: &Path, manifest: &AtlasManifest) -> Result<(), AtlasError> {
    let payload = toml::to_string_pretty(manifest)
        .map_err(|error| AtlasError::Corrupt(format!("manifest encoding failed: {error}")))?;
    if payload.len() as u64 > MAX_MANIFEST_BYTES {
        return Err(AtlasError::Corrupt(
            "manifest exceeds its size limit".into(),
        ));
    }
    crate::persist::atomic_write(&planet_dir.join(MANIFEST_FILE), payload.as_bytes(), false)?;
    Ok(())
}

pub(in crate::planet_atlas) fn sync_directory(path: &Path) -> Result<(), AtlasError> {
    #[cfg(unix)]
    fs::File::open(path)?.sync_all()?;
    #[cfg(not(unix))]
    let _ = path;
    Ok(())
}

pub(in crate::planet_atlas) fn read_bounded(path: &Path, max_bytes: u64) -> Result<Vec<u8>, AtlasError> {
    let metadata = fs::metadata(path)?;
    if metadata.len() > max_bytes {
        return Err(AtlasError::Corrupt(format!(
            "{} is {} bytes; limit is {max_bytes}",
            path.display(),
            metadata.len()
        )));
    }
    Ok(fs::read(path)?)
}
